version: '2.1'
services:
  azure-relay:
    build:
      context: ./azure-relay
      dockerfile: Dockerfile.template
    restart: unless-stopped
    network_mode: host
    labels:
      io.balena.features.supervisor-api: '1'
